<template>
  <div>
    <ul>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
      <li>d</li>
    </ul>
  </div>
</template>

<script>
  export default {
    name: "Category"
  }
</script>

<style scoped>

</style>
